FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ARG AGENT_BASE_PATH=/

ENV AGENT_BASE_PATH=$AGENT_BASE_PATH
RUN npm run build

FROM nginx:alpine
ENV NGINX_ENVSUBST_FILTER=AGENT_SLUG
COPY templates/ /etc/nginx/templates/
COPY --from=build /app/dist /usr/share/nginx/html
